# Generated by Django 5.1.2 on 2024-10-17 05:12

import django.db.models.deletion
import django_ckeditor_5.fields
import utils.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=14, validators=[utils.validations.phone_number_validation])),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='banner/')),
                ('short_description', models.CharField(max_length=350)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommissionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='news/')),
                ('short_description', models.CharField(max_length=300)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('telegram_url', models.URLField()),
                ('instagram_url', models.URLField()),
                ('facebook_url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=14, validators=[utils.validations.phone_number_validation])),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=500)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('file', models.FileField(upload_to='project/')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Finished'), (2, 'In_proces')], default=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.PositiveIntegerField(choices=[(1, 'Tashkent'), (2, 'Bukhara region'), (3, 'Fergana region'), (4, 'Andijan region'), (5, 'Jizzakh region'), (6, 'Namangan region'), (7, 'Navoiy region'), (8, 'Qashqadaryo region'), (9, 'Samarqand region'), (10, 'Sirdaryo region'), (11, 'Surxondaryo region'), (12, 'Tashkent region'), (13, 'Xorazim region'), (14, 'Republic of Karakalpakstan')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommissionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=100)),
                ('type', models.PositiveIntegerField(choices=[(1, 'Constant'), (2, 'Regional')], default=1)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('position', models.CharField(max_length=80)),
                ('birthdate', models.DateTimeField()),
                ('nation', models.CharField(max_length=100)),
                ('education_degree', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telegram_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('commission_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.commissioncategory')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppealMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('phone_number', models.CharField(max_length=14, validators=[utils.validations.phone_number_validation])),
                ('address', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.PositiveIntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1)),
                ('birthdate', models.DateField()),
                ('commission_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.commissionmember')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.region')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
