# Generated by Django 5.1.2 on 2024-11-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incoming_appeals', models.PositiveIntegerField(default=0, verbose_name='полученные обращения')),
                ('resolved_appeals', models.PositiveIntegerField(default=0, verbose_name='решенные обращения')),
                ('explained_appeals', models.PositiveIntegerField(default=0, verbose_name='объясненные обрашения')),
                ('rejected_appeals', models.PositiveIntegerField(default=0, verbose_name='отклоненные обрашения')),
            ],
            options={
                'verbose_name': 'Статистика обрашения',
                'verbose_name_plural': 'Статистики обрашений',
                'ordering': ('-created_at',),
            },
        ),
    ]
