# Generated by Django 5.1.2 on 2024-10-19 19:10

import django.db.models.deletion
import tinymce.models
import utils.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(max_length=225)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='заголовок')),
                ('image', models.ImageField(upload_to='news/', verbose_name='изображение')),
                ('short_description', models.CharField(max_length=200, verbose_name='краткое описание')),
                ('short_description_uz', models.CharField(max_length=200, null=True, verbose_name='краткое описание')),
                ('short_description_ru', models.CharField(max_length=200, null=True, verbose_name='краткое описание')),
                ('short_description_en', models.CharField(max_length=200, null=True, verbose_name='краткое описание')),
                ('description', tinymce.models.HTMLField(verbose_name='описание')),
                ('description_uz', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('description_ru', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('description_en', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('telegram_url', models.URLField(default='telegram.org', verbose_name='телеграм_url')),
                ('instagram_url', models.URLField(default='instagram.com', verbose_name='инстаграм_url')),
                ('facebook_url', models.URLField(default='facebook.com', verbose_name='фэйсбук_url')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ('created_at',),
            },
        ),
        migrations.RemoveField(
            model_name='appealmember',
            name='commission_member',
        ),
        migrations.RemoveField(
            model_name='appealmember',
            name='region',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Opinion',
        ),
        migrations.AlterModelOptions(
            name='appeal',
            options={'ordering': ('created_at',), 'verbose_name': 'Запрос', 'verbose_name_plural': 'Запросы'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('created_at',), 'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterModelOptions(
            name='commissioncategory',
            options={'ordering': ('created_at',), 'verbose_name': 'Категория комиссии', 'verbose_name_plural': 'Категория комиссий'},
        ),
        migrations.AlterModelOptions(
            name='commissionmember',
            options={'ordering': ('created_at',), 'verbose_name': 'член комиссии', 'verbose_name_plural': 'члены комисси'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ('created_at',), 'verbose_name': 'Проект', 'verbose_name_plural': 'проекты'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('created_at',), 'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='short_description',
        ),
        migrations.AddField(
            model_name='appeal',
            name='commission_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.commissionmember'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='full_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Полное имя'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='full_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Полное имя'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='full_name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Полное имя'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='message_en',
            field=models.TextField(null=True, verbose_name='сообщение'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='message_ru',
            field=models.TextField(null=True, verbose_name='сообщение'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='message_uz',
            field=models.TextField(null=True, verbose_name='сообщение'),
        ),
        migrations.AddField(
            model_name='banner',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='commissioncategory',
            name='name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Назавние'),
        ),
        migrations.AddField(
            model_name='commissioncategory',
            name='name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Назавние'),
        ),
        migrations.AddField(
            model_name='commissioncategory',
            name='name_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Назавние'),
        ),
        migrations.AddField(
            model_name='commissionmember',
            name='description_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='commissionmember',
            name='description_ru',
            field=tinymce.models.HTMLField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='commissionmember',
            name='description_uz',
            field=tinymce.models.HTMLField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='commissionmember',
            name='education_degree_en',
            field=models.CharField(max_length=100, null=True, verbose_name='степень образования'),
        ),
        migrations.AddField(
            model_name='commissionmember',
            name='education_degree_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='степень образования'),
        ),
        migrations.AddField(
            model_name='commissionmember',
            name='education_degree_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='степень образования'),
        ),
        migrations.AddField(
            model_name='commissionmember',
            name='full_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='полное имя'),
        ),
        migrations.AddField(
            model_name='commissionmember',
            name='full_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='полное имя'),
        ),
        migrations.AddField(
            model_name='commissionmember',
            name='full_name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='полное имя'),
        ),
        migrations.AddField(
            model_name='commissionmember',
            name='image',
            field=models.ImageField(default=1, upload_to='commission_member/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commissionmember',
            name='nation_en',
            field=models.CharField(max_length=100, null=True, verbose_name='нация'),
        ),
        migrations.AddField(
            model_name='commissionmember',
            name='nation_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='нация'),
        ),
        migrations.AddField(
            model_name='commissionmember',
            name='nation_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='нация'),
        ),
        migrations.AddField(
            model_name='commissionmember',
            name='position_en',
            field=models.CharField(max_length=80, null=True, verbose_name='позиция'),
        ),
        migrations.AddField(
            model_name='commissionmember',
            name='position_ru',
            field=models.CharField(max_length=80, null=True, verbose_name='позиция'),
        ),
        migrations.AddField(
            model_name='commissionmember',
            name='position_uz',
            field=models.CharField(max_length=80, null=True, verbose_name='позиция'),
        ),
        migrations.AddField(
            model_name='commissionmember',
            name='speciality_en',
            field=models.CharField(max_length=150, null=True, verbose_name='специальность'),
        ),
        migrations.AddField(
            model_name='commissionmember',
            name='speciality_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='специальность'),
        ),
        migrations.AddField(
            model_name='commissionmember',
            name='speciality_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='специальность'),
        ),
        migrations.AddField(
            model_name='projects',
            name='description_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='projects',
            name='description_ru',
            field=tinymce.models.HTMLField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='projects',
            name='description_uz',
            field=tinymce.models.HTMLField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='projects',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='projects',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='навзание'),
        ),
        migrations.AddField(
            model_name='projects',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='навзание'),
        ),
        migrations.AddField(
            model_name='projects',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='навзание'),
        ),
        migrations.AddField(
            model_name='projects',
            name='short_description_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='projects',
            name='short_description_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='projects',
            name='short_description_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Назавние'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Назавние'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Назавние'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='электронная почта'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='message',
            field=models.TextField(verbose_name='сообщение'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='phone_number',
            field=models.CharField(max_length=14, validators=[utils.validations.phone_number_validation], verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banner/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='commissioncategory',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Назавние'),
        ),
        migrations.AlterField(
            model_name='commissionmember',
            name='birthdate',
            field=models.DateTimeField(verbose_name='дата рождения'),
        ),
        migrations.AlterField(
            model_name='commissionmember',
            name='commission_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.commissioncategory', verbose_name='Категория комиссии'),
        ),
        migrations.AlterField(
            model_name='commissionmember',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='commissionmember',
            name='education_degree',
            field=models.CharField(max_length=100, verbose_name='степень образования'),
        ),
        migrations.AlterField(
            model_name='commissionmember',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='электронная почта'),
        ),
        migrations.AlterField(
            model_name='commissionmember',
            name='facebook_url',
            field=models.URLField(default='facebook.com', verbose_name='фэйсбук_url'),
        ),
        migrations.AlterField(
            model_name='commissionmember',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='полное имя'),
        ),
        migrations.AlterField(
            model_name='commissionmember',
            name='instagram_url',
            field=models.URLField(default='instagram.com', verbose_name='инстаграм_url'),
        ),
        migrations.AlterField(
            model_name='commissionmember',
            name='nation',
            field=models.CharField(max_length=100, verbose_name='нация'),
        ),
        migrations.AlterField(
            model_name='commissionmember',
            name='position',
            field=models.CharField(max_length=80, verbose_name='позиция'),
        ),
        migrations.AlterField(
            model_name='commissionmember',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.region', verbose_name='регион'),
        ),
        migrations.AlterField(
            model_name='commissionmember',
            name='speciality',
            field=models.CharField(max_length=150, verbose_name='специальность'),
        ),
        migrations.AlterField(
            model_name='commissionmember',
            name='telegram_url',
            field=models.URLField(default='telegram.org', verbose_name='телеграм_url'),
        ),
        migrations.AlterField(
            model_name='commissionmember',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Постоянный'), (2, 'Региональный')], default=1, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='file',
            field=models.FileField(upload_to='project/', verbose_name='файл'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=100, verbose_name='навзание'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='short_description',
            field=models.CharField(max_length=200, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Оконченный'), (2, 'В процессе')], default=2, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Назавние'),
        ),
        migrations.AddField(
            model_name='post',
            name='commission_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.commissionmember', verbose_name='член комиссии'),
        ),
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.ManyToManyField(blank=True, to='services.ipaddress', verbose_name='количество просмотров'),
        ),
        migrations.DeleteModel(
            name='AppealMember',
        ),
    ]
