# Generated by Django 5.1.2 on 2024-11-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_appealstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250, verbose_name='Назавние')),
            ],
            options={
                'verbose_name': 'Категория мандата',
                'verbose_name_plural': 'Категория мандатов',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='commissionmember',
            name='mandat',
            field=models.ManyToManyField(to='services.mandatcategory', verbose_name='Мандат'),
        ),
    ]
