# Generated by Django 5.1.2 on 2024-10-22 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_ipaddress_post_remove_appealmember_commission_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='commission_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_post', to='services.commissionmember', verbose_name='член комиссии'),
        ),
    ]
