# Generated by Django 5.1.2 on 2024-10-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_post_commission_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'ordering': ('created_at',), 'verbose_name': 'Ip адрес', 'verbose_name_plural': 'Ip адресы'},
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='ip',
            field=models.CharField(max_length=225, verbose_name='ip'),
        ),
    ]
