# Generated by Django 5.1.2 on 2024-11-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_mandatcategory_commissionmember_mandat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionmember',
            name='mandat',
            field=models.ManyToManyField(related_name='mandats', to='services.mandatcategory', verbose_name='Мандат'),
        ),
    ]
