# Generated by Django 5.1.2 on 2024-11-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_postcategory_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('video', models.URLField(verbose_name='видео')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ('-created_at',),
            },
        ),
    ]
