# Generated by Django 5.1.2 on 2024-10-23 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_delete_banner_alter_appeal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='commission_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_post', to='services.commissionmember', verbose_name='член комиссии'),
        ),
    ]
