# Generated by Django 5.1.2 on 2024-11-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='название'),
        ),
    ]
