# Generated by Django 5.1.2 on 2024-11-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_video_title_en_video_title_ru_video_title_uz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionmember',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Постоянный'), (2, 'Региональный'), (3, 'Руководство')], default=1, verbose_name='тип'),
        ),
    ]
