# Generated by Django 5.1.2 on 2024-11-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_commissionmember_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='это баннер'),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='name_en',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='name_ru',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='postcategory',
            name='name_uz',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
