# Generated by Django 5.1.2 on 2024-11-28 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_post_is_banner_postcategory_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissioncategory',
            name='description',
            field=models.TextField(default='', verbose_name='описание'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='category_image/', verbose_name='изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_image', to='services.commissioncategory', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'изображение катогории',
                'verbose_name_plural': 'изображение катогорий',
                'ordering': ('-created_at',),
            },
        ),
    ]
