# Generated by Django 5.1.2 on 2024-11-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_commissioncategory_description_categoryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissioncategory',
            name='description_en',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='commissioncategory',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='commissioncategory',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
    ]
