# Generated by Django 5.1.2 on 2024-11-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_categoryimage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionmember',
            name='mandat',
        ),
        migrations.AddField(
            model_name='mandatcategory',
            name='commission_members',
            field=models.ManyToManyField(related_name='members', to='services.commissionmember', verbose_name='члены комиссии'),
        ),
    ]
