# Generated by Django 5.1.2 on 2024-11-28 23:39

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_mandatcategory_name_en_mandatcategory_name_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Normative_documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='normative/', verbose_name='файл')),
                ('content', tinymce.models.HTMLField(verbose_name='контент')),
            ],
            options={
                'verbose_name': 'нормативный документ',
                'verbose_name_plural': 'нормативные документы',
                'ordering': ('-created_at',),
            },
        ),
    ]
