# Generated by Django 5.1.2 on 2024-11-28 15:38

import django.db.models.deletion
import services.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_normative_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormativeDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('name_uz', models.CharField(blank=True, max_length=200, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('name_en', models.CharField(blank=True, max_length=200, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='normative/', validators=[services.utils.validate_file_type_and_size], verbose_name='файл')),
                ('doc_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Word'), ('xls', 'Excel')], editable=False, max_length=5)),
            ],
            options={
                'verbose_name': 'нормативный документ',
                'verbose_name_plural': 'нормативные документы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='Normative_documents',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='commission_member',
        ),
        migrations.RemoveField(
            model_name='post',
            name='commission_member',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.postcategory'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='file',
            field=models.FileField(upload_to='project/', validators=[services.utils.validate_file_type_and_size], verbose_name='файл'),
        ),
    ]
