# Generated by Django 5.1.2 on 2024-11-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_normativedocuments_delete_normative_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normativedocuments',
            name='doc_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Word'), ('xls', 'Excel')], editable=False, max_length=5, verbose_name='тип документа'),
        ),
        migrations.AlterField(
            model_name='normativedocuments',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='normativedocuments',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='normativedocuments',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='normativedocuments',
            name='name_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='название'),
        ),
    ]
