# Generated by Django 5.1.2 on 2024-11-28 18:32

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_alter_normativedocuments_doc_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=100, verbose_name='полное имя')),
                ('full_name_uz', models.CharField(max_length=100, null=True, verbose_name='полное имя')),
                ('full_name_ru', models.CharField(max_length=100, null=True, verbose_name='полное имя')),
                ('full_name_en', models.CharField(max_length=100, null=True, verbose_name='полное имя')),
                ('description', tinymce.models.HTMLField(verbose_name='описание')),
                ('description_uz', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('description_ru', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('description_en', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('phone_number', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=150, verbose_name='позиция')),
                ('position_uz', models.CharField(max_length=150, null=True, verbose_name='позиция')),
                ('position_ru', models.CharField(max_length=150, null=True, verbose_name='позиция')),
                ('position_en', models.CharField(max_length=150, null=True, verbose_name='позиция')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='телеграм_url')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='инстаграм_url')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='фейсбук_url')),
                ('order', models.PositiveIntegerField(default=1)),
                ('image', models.ImageField(upload_to='managements/')),
            ],
            options={
                'verbose_name': 'Управление',
                'verbose_name_plural': 'Управлении',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='commissionmember',
            options={'ordering': ('order',), 'verbose_name': 'член комиссии', 'verbose_name_plural': 'члены комисси'},
        ),
        migrations.RemoveField(
            model_name='commissionmember',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='commissionmember',
            name='education_degree',
        ),
        migrations.RemoveField(
            model_name='commissionmember',
            name='education_degree_en',
        ),
        migrations.RemoveField(
            model_name='commissionmember',
            name='education_degree_ru',
        ),
        migrations.RemoveField(
            model_name='commissionmember',
            name='education_degree_uz',
        ),
        migrations.RemoveField(
            model_name='commissionmember',
            name='email',
        ),
        migrations.RemoveField(
            model_name='commissionmember',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='commissionmember',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='commissionmember',
            name='nation',
        ),
        migrations.RemoveField(
            model_name='commissionmember',
            name='nation_en',
        ),
        migrations.RemoveField(
            model_name='commissionmember',
            name='nation_ru',
        ),
        migrations.RemoveField(
            model_name='commissionmember',
            name='nation_uz',
        ),
        migrations.RemoveField(
            model_name='commissionmember',
            name='position',
        ),
        migrations.RemoveField(
            model_name='commissionmember',
            name='position_en',
        ),
        migrations.RemoveField(
            model_name='commissionmember',
            name='position_ru',
        ),
        migrations.RemoveField(
            model_name='commissionmember',
            name='position_uz',
        ),
        migrations.RemoveField(
            model_name='commissionmember',
            name='speciality',
        ),
        migrations.RemoveField(
            model_name='commissionmember',
            name='speciality_en',
        ),
        migrations.RemoveField(
            model_name='commissionmember',
            name='speciality_ru',
        ),
        migrations.RemoveField(
            model_name='commissionmember',
            name='speciality_uz',
        ),
        migrations.RemoveField(
            model_name='commissionmember',
            name='telegram_url',
        ),
        migrations.RemoveField(
            model_name='commissionmember',
            name='type',
        ),
        migrations.RemoveField(
            model_name='mandatcategory',
            name='commission_members',
        ),
        migrations.AddField(
            model_name='commissionmember',
            name='mandat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandat', to='services.mandatcategory'),
        ),
        migrations.AddField(
            model_name='commissionmember',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
