# Generated by Django 5.1.2 on 2024-11-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_management_alter_commissionmember_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='электронная почта'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='full_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='full_name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='full_name_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='сообщение'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='message_en',
            field=models.TextField(blank=True, null=True, verbose_name='сообщение'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='message_ru',
            field=models.TextField(blank=True, null=True, verbose_name='сообщение'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='message_uz',
            field=models.TextField(blank=True, null=True, verbose_name='сообщение'),
        ),
    ]
