# Generated by Django 5.1.2 on 2024-11-29 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_alter_appeal_email_alter_appeal_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='full_name_en',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='full_name_ru',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='full_name_uz',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='message_en',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='message_ru',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='message_uz',
        ),
    ]
