# Generated by Django 5.1.2 on 2024-11-29 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_remove_appeal_full_name_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='management',
            options={'ordering': ('order',), 'verbose_name': 'Управление', 'verbose_name_plural': 'Управлении'},
        ),
    ]
