# Generated by Django 5.1.2 on 2024-12-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_alter_commissionmember_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissioncategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='commission/category/', verbose_name='иконка'),
        ),
        migrations.AddField(
            model_name='commissionmember',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commissionmember',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commissionmember',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='номер телефона'),
        ),
        migrations.AddField(
            model_name='commissionmember',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commissioncategory',
            name='name',
            field=models.CharField(max_length=250, verbose_name='назавние'),
        ),
        migrations.AlterField(
            model_name='commissioncategory',
            name='name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='назавние'),
        ),
        migrations.AlterField(
            model_name='commissioncategory',
            name='name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='назавние'),
        ),
        migrations.AlterField(
            model_name='commissioncategory',
            name='name_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='назавние'),
        ),
    ]
