# Generated by Django 5.1.2 on 2024-12-02 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_alter_normativedocuments_doc_type'),
        ('services', '0023_commissioncategory_icon_commissionmember_facebook_and_more'),
    ]

    operations = [
    ]
