# Generated by Django 5.1.2 on 2024-12-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_alter_postcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='description',
            field=models.CharField(max_length=300, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='management',
            name='description_en',
            field=models.CharField(max_length=300, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='management',
            name='description_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='management',
            name='description_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='management',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='номер телефона'),
        ),
    ]
