# Generated by Django 5.1.2 on 2024-12-03 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_alter_management_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionmember',
            name='image',
            field=models.ImageField(upload_to='commission_member/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='commissionmember',
            name='mandat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandat', to='services.mandatcategory', verbose_name='мандат'),
        ),
        migrations.AlterField(
            model_name='commissionmember',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='порядковый номер'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.postcategory', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateField(verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='name',
            field=models.CharField(max_length=225, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='name_en',
            field=models.CharField(max_length=225, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='name_ru',
            field=models.CharField(max_length=225, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='name_uz',
            field=models.CharField(max_length=225, null=True, verbose_name='название'),
        ),
    ]
