# Generated by Django 5.1.2 on 2024-12-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0029_alter_region_static_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='video/image/', verbose_name='изображение'),
        ),
    ]
