# Generated by Django 5.1.2 on 2024-12-10 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_video_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='image',
        ),
    ]
