# Generated by Django 5.1.2 on 2024-12-03 14:28

import django.db.models.deletion
import tinymce.models
import utils.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('short_description', models.CharField(max_length=300, verbose_name='краткое описание')),
                ('short_description_uz', models.CharField(max_length=300, null=True, verbose_name='краткое описание')),
                ('short_description_ru', models.CharField(max_length=300, null=True, verbose_name='краткое описание')),
                ('short_description_en', models.CharField(max_length=300, null=True, verbose_name='краткое описание')),
                ('description', tinymce.models.HTMLField(verbose_name='описание')),
                ('description_uz', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('description_ru', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('description_en', tinymce.models.HTMLField(null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AdditionalLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, verbose_name='название')),
                ('title_uz', models.CharField(max_length=250, null=True, verbose_name='название')),
                ('title_ru', models.CharField(max_length=250, null=True, verbose_name='название')),
                ('title_en', models.CharField(max_length=250, null=True, verbose_name='название')),
                ('link', models.URLField(verbose_name='ссылка')),
                ('image', models.ImageField(upload_to='additional_links/', verbose_name='изображение')),
                ('is_visible', models.BooleanField(default=True, verbose_name='опубликован')),
            ],
            options={
                'verbose_name': 'Дополнительные ссылка',
                'verbose_name_plural': 'Дополнительные ссылки',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, verbose_name='электронная почта')),
                ('phone_number', models.CharField(max_length=14, validators=[utils.validations.phone_number_validation], verbose_name='номер телефона')),
                ('address', models.CharField(max_length=255, verbose_name='название адреса')),
                ('address_uz', models.CharField(max_length=255, null=True, verbose_name='название адреса')),
                ('address_ru', models.CharField(max_length=255, null=True, verbose_name='название адреса')),
                ('address_en', models.CharField(max_length=255, null=True, verbose_name='название адреса')),
                ('latitude', models.FloatField(verbose_name='широта')),
                ('longitude', models.FloatField(verbose_name='долгота')),
                ('telegram_url', models.URLField(default='telegram.org', verbose_name='телеграм_url')),
                ('instagram_url', models.URLField(default='instagram.com', verbose_name='инстаграм_url')),
                ('facebook_url', models.URLField(default='facebook.com', verbose_name='фэйсбук_url')),
                ('youtube_url', models.URLField(default='youtube.com', verbose_name='ютубе_url')),
                ('twitter_url', models.URLField(default='twitter.com', verbose_name='твиттер_url')),
                ('linkedin_url', models.URLField(default='linkedin.com', verbose_name='линкедин_url')),
            ],
            options={
                'verbose_name': 'Связаться с нами',
                'verbose_name_plural': 'Связаться с нами',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField(max_length=700, verbose_name='вопрос')),
                ('question_uz', models.TextField(max_length=700, null=True, verbose_name='вопрос')),
                ('question_ru', models.TextField(max_length=700, null=True, verbose_name='вопрос')),
                ('question_en', models.TextField(max_length=700, null=True, verbose_name='вопрос')),
                ('answer', models.TextField(max_length=1000, verbose_name='ответ')),
                ('answer_uz', models.TextField(max_length=1000, null=True, verbose_name='ответ')),
                ('answer_ru', models.TextField(max_length=1000, null=True, verbose_name='ответ')),
                ('answer_en', models.TextField(max_length=1000, null=True, verbose_name='ответ')),
                ('is_visible', models.BooleanField(default=True, verbose_name='опубликован')),
            ],
            options={
                'verbose_name': 'Часто задаваемые вопросы',
                'verbose_name_plural': 'Часто задаваемые вопросы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('name_uz', models.CharField(max_length=150, null=True, verbose_name='название')),
                ('name_ru', models.CharField(max_length=150, null=True, verbose_name='название')),
                ('name_en', models.CharField(max_length=150, null=True, verbose_name='название')),
                ('started_at', models.DateField(verbose_name='дата начала')),
                ('ended_at', models.DateField(verbose_name='дата окончания')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Активный'), (2, 'Завершено')], default=1, verbose_name='Состояние')),
                ('result', tinymce.models.HTMLField(verbose_name='Результат')),
                ('result_uz', tinymce.models.HTMLField(null=True, verbose_name='Результат')),
                ('result_ru', tinymce.models.HTMLField(null=True, verbose_name='Результат')),
                ('result_en', tinymce.models.HTMLField(null=True, verbose_name='Результат')),
                ('link_to_poll', models.URLField(verbose_name='Ссылка на опрос')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AboutUsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='about_us/', verbose_name='Изоражение')),
                ('about_us', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_image', to='base.aboutus', verbose_name='о нас')),
            ],
            options={
                'verbose_name': 'Изображение о нас',
                'verbose_name_plural': 'изображения о нас',
                'ordering': ('-created_at',),
            },
        ),
    ]
