# Generated by Django 5.1.2 on 2024-10-19 19:10

import django.db.models.deletion
import tinymce.models
import utils.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=100, verbose_name='текст')),
                ('text_uz', models.CharField(max_length=100, null=True, verbose_name='текст')),
                ('text_ru', models.CharField(max_length=100, null=True, verbose_name='текст')),
                ('text_en', models.CharField(max_length=100, null=True, verbose_name='текст')),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': 'Варианты',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('title_uz', models.CharField(max_length=100, null=True, verbose_name='заголовок')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='заголовок')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='заголовок')),
                ('description', tinymce.models.HTMLField(verbose_name='описание')),
                ('description_uz', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('description_ru', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('description_en', tinymce.models.HTMLField(null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'ordering': ('created_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'ordering': ['created_at'], 'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterModelOptions(
            name='additionallinks',
            options={'ordering': ['created_at'], 'verbose_name': 'Дополнительные ссылка', 'verbose_name_plural': 'Дополнительные ссылки'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['created_at'], 'verbose_name': 'Связаться с нами', 'verbose_name_plural': 'Связаться с нами'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['created_at'], 'verbose_name': 'Часто задаваемые вопросы', 'verbose_name_plural': 'Часто задаваемые вопросы'},
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_ru',
            field=tinymce.models.HTMLField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_uz',
            field=tinymce.models.HTMLField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='file',
            field=models.FileField(default=1, upload_to='about_us/', verbose_name='файл'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='is_video',
            field=models.BooleanField(default=False, verbose_name='видео'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='youtube_url',
            field=models.URLField(default='youtube.com', verbose_name='ютубе_url'),
        ),
        migrations.AddField(
            model_name='additionallinks',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='изображение'),
        ),
        migrations.AddField(
            model_name='additionallinks',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='additionallinks',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='additionallinks',
            name='title_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='address_en',
            field=models.CharField(max_length=255, null=True, verbose_name='адрес'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='address_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='адрес'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='address_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='адрес'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='facebook_url',
            field=models.URLField(default='facebook.com', verbose_name='фэйсбук_url'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='instagram_url',
            field=models.URLField(default='instagram.com', verbose_name='инстаграм_url'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='latitude',
            field=models.FloatField(default=1, verbose_name='широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactus',
            name='longitude',
            field=models.FloatField(default=1, verbose_name='долгота'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactus',
            name='telegram_url',
            field=models.URLField(default='telegram.org', verbose_name='телеграм_url'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='youtube_url',
            field=models.URLField(default='youtube.com', verbose_name='ютубе_url'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.CharField(max_length=200, null=True, verbose_name='ответ'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='ответ'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='ответ'),
        ),
        migrations.AddField(
            model_name='faq',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='видимый'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=200, null=True, verbose_name='вопрос'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='вопрос'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='вопрос'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='facebook_url',
            field=models.URLField(default='facebook.com', verbose_name='фэйсбук_url'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='instagram_url',
            field=models.URLField(default='instagram.com', verbose_name='инстаграм_url'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='telegram_url',
            field=models.URLField(default='telegram.org', verbose_name='телеграм_url'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(max_length=200, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='additionallinks',
            name='image',
            field=models.ImageField(upload_to='additional_links/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='additionallinks',
            name='link',
            field=models.URLField(verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='additionallinks',
            name='title',
            field=models.CharField(max_length=250, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='address',
            field=models.CharField(max_length=255, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='электронная почта'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone_number',
            field=models.CharField(max_length=14, validators=[utils.validations.phone_number_validation], verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.CharField(max_length=200, verbose_name='ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=200, verbose_name='вопрос'),
        ),
        migrations.CreateModel(
            name='PollResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=15, verbose_name='пользователь')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.poll', verbose_name='опрос')),
            ],
            options={
                'verbose_name': 'Результат опроса',
                'verbose_name_plural': 'Результаты опроса',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', tinymce.models.HTMLField(verbose_name='текст')),
                ('text_uz', tinymce.models.HTMLField(null=True, verbose_name='текст')),
                ('text_ru', tinymce.models.HTMLField(null=True, verbose_name='текст')),
                ('text_en', tinymce.models.HTMLField(null=True, verbose_name='текст')),
                ('type', models.PositiveIntegerField(choices=[(1, 'Единственный выбор'), (2, 'Множественный выбор')], default=1, verbose_name='тип')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.poll', verbose_name='опрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='PollAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.ManyToManyField(to='base.option', verbose_name='вариант')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pollresult', verbose_name='результат')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.question', verbose_name='вопрос')),
            ],
            options={
                'verbose_name': 'Ответ на опрос',
                'verbose_name_plural': 'Ответы на опросы',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.question', verbose_name='вопрос'),
        ),
    ]
