# Generated by Django 5.1.2 on 2024-10-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_option_poll_alter_aboutus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='participant_count',
            field=models.PositiveIntegerField(default=0, verbose_name='количество участники'),
        ),
    ]
