# Generated by Django 5.1.2 on 2024-11-26 20:58

import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_banner_title_en_banner_title_ru_banner_title_uz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='pollanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='pollanswer',
            name='result',
        ),
        migrations.RemoveField(
            model_name='pollresult',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='pollresult',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='description',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='participant_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='title',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='title_uz',
        ),
        migrations.AddField(
            model_name='poll',
            name='ended_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата окончания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='link_to_poll',
            field=models.URLField(default='', verbose_name='Ссылка на опрос'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='name',
            field=models.CharField(default='a', max_length=150, verbose_name='название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='poll',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='poll',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='poll',
            name='result',
            field=tinymce.models.HTMLField(default='', verbose_name='Результат'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='result_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Результат'),
        ),
        migrations.AddField(
            model_name='poll',
            name='result_ru',
            field=tinymce.models.HTMLField(null=True, verbose_name='Результат'),
        ),
        migrations.AddField(
            model_name='poll',
            name='result_uz',
            field=tinymce.models.HTMLField(null=True, verbose_name='Результат'),
        ),
        migrations.AddField(
            model_name='poll',
            name='started_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата начала'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Активный'), (2, 'Завершено')], default=1, verbose_name='Состояние'),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='PollAnswer',
        ),
        migrations.DeleteModel(
            name='PollResult',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
