# Generated by Django 5.1.2 on 2024-10-23 09:42

import utils.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_poll_participant_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='banner/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=255, verbose_name='текст')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, verbose_name='электронная почта')),
                ('phone_number', models.CharField(max_length=14, validators=[utils.validations.phone_number_validation], verbose_name='номер телефона')),
                ('address', models.CharField(max_length=255, verbose_name='название адреса')),
                ('address_uz', models.CharField(max_length=255, null=True, verbose_name='название адреса')),
                ('address_ru', models.CharField(max_length=255, null=True, verbose_name='название адреса')),
                ('address_en', models.CharField(max_length=255, null=True, verbose_name='название адреса')),
                ('latitude', models.FloatField(verbose_name='широта')),
                ('longitude', models.FloatField(verbose_name='долгота')),
                ('telegram_url', models.URLField(default='telegram.org', verbose_name='телеграм_url')),
                ('instagram_url', models.URLField(default='instagram.com', verbose_name='инстаграм_url')),
                ('facebook_url', models.URLField(default='facebook.com', verbose_name='фэйсбук_url')),
                ('youtube_url', models.URLField(default='youtube.com', verbose_name='ютубе_url')),
            ],
            options={
                'verbose_name': 'Связаться с нами',
                'verbose_name_plural': 'Связаться с нами',
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'ordering': ('-created_at',), 'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterModelOptions(
            name='additionallinks',
            options={'ordering': ('-created_at',), 'verbose_name': 'Дополнительные ссылка', 'verbose_name_plural': 'Дополнительные ссылки'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ('-created_at',), 'verbose_name': 'Часто задаваемые вопросы', 'verbose_name_plural': 'Часто задаваемые вопросы'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ('-created_at',), 'verbose_name': 'Вариант', 'verbose_name_plural': 'Варианты'},
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ('-created_at',), 'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.AlterModelOptions(
            name='pollanswer',
            options={'ordering': ('-created_at',), 'verbose_name': 'Ответ на опрос', 'verbose_name_plural': 'Ответы на опросы'},
        ),
        migrations.AlterModelOptions(
            name='pollresult',
            options={'ordering': ('-created_at',), 'verbose_name': 'Результат опроса', 'verbose_name_plural': 'Результаты опроса'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-created_at',), 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='file',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='is_video',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='telegram_url',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='title',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='youtube_url',
        ),
        migrations.AlterField(
            model_name='additionallinks',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='опубликован'),
        ),
        migrations.AlterField(
            model_name='additionallinks',
            name='title',
            field=models.CharField(max_length=250, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='additionallinks',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='additionallinks',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='additionallinks',
            name='title_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(max_length=1000, verbose_name='ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(max_length=1000, null=True, verbose_name='ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(max_length=1000, null=True, verbose_name='ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_uz',
            field=models.TextField(max_length=1000, null=True, verbose_name='ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='опубликован'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(max_length=700, verbose_name='вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_en',
            field=models.TextField(max_length=700, null=True, verbose_name='вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ru',
            field=models.TextField(max_length=700, null=True, verbose_name='вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_uz',
            field=models.TextField(max_length=700, null=True, verbose_name='вопрос'),
        ),
    ]
