# Generated by Django 5.1.2 on 2024-11-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_pollanswer_answer_remove_pollanswer_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
    ]
