# Generated by Django 5.1.2 on 2024-11-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_banner_title_alter_banner_title_en_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
