# Generated by Django 5.1.2 on 2024-11-29 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_delete_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='about_us/', verbose_name='Изоражение')),
                ('about_us', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.aboutus', verbose_name='о нас')),
            ],
            options={
                'verbose_name': 'Изображение о нас',
                'verbose_name_plural': 'изображения о нас',
                'ordering': ('-created_at',),
            },
        ),
    ]
