# Generated by Django 5.1.2 on 2024-11-29 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_aboutusimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusimage',
            name='about_us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_image', to='base.aboutus', verbose_name='о нас'),
        ),
    ]
