# Generated by Django 5.1.2 on 2024-11-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_aboutusimage_about_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseinfo',
            name='linkedin_url',
            field=models.URLField(default='linkedin.com', verbose_name='линкедин_url'),
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='twitter_url',
            field=models.URLField(default='twitter.com', verbose_name='твиттер_url'),
        ),
    ]
