# Generated by Django 5.1.2 on 2024-12-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_baseinfo_linkedin_url_baseinfo_twitter_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='short_description',
            field=models.CharField(default=1, max_length=300, verbose_name='краткое описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='short_description_en',
            field=models.CharField(max_length=300, null=True, verbose_name='краткое описание'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='short_description_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='краткое описание'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='short_description_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='краткое описание'),
        ),
    ]
