name: Development CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Development Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > ssh_key
          chmod 600 ssh_key
          mkdir -p ~/.ssh
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
          
          rsync -avz -e "ssh -i ssh_key" --exclude='venv' --exclude='.git' ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/zerodev/dev/${{ secrets.PROJECT_NAME }}
          ssh -i ssh_key ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            set -e
            source /home/zerodev/dev/virtualenvs/${{ secrets.PROJECT_NAME }}/bin/activate
            cd /home/zerodev/dev/${{ secrets.PROJECT_NAME }}
            pip install -r requirements.txt
            python3 manage.py migrate
            python3 manage.py collectstatic --noinput
            echo "${{ secrets.PASSWORD }}" | sudo -S systemctl restart ${{ secrets.PROJECT_NAME }}-dev.service
            echo "Deployment successful"
          EOF
